###
GET {{host}}/cat_get ? cname=kamar

###
POST {{host}}/api/cat_add
Content-Type: application/json

{
  "kamutu": 12,
  "kamini": 7,
  "stronjo": 5,
  "kamar": 23
}

###
PUT {{host}}/api/cat_put?name=kamar&age=46





